// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAurOHgL1SXCTJ3yBfXU-bQyCP3bKfLhA8',
    appId: '1:1010580786552:android:b11be754a9442a89e30c8d',
    messagingSenderId: '1010580786552',
    projectId: 'recharge-direct-2f3b2',
    storageBucket: 'recharge-direct-2f3b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFhHzmeom9tT7mc0iHnoeExPAHi1x9oX4',
    appId: '1:1010580786552:ios:3f3fdfdc761ddc73e30c8d',
    messagingSenderId: '1010580786552',
    projectId: 'recharge-direct-2f3b2',
    storageBucket: 'recharge-direct-2f3b2.appspot.com',
    iosClientId: '1010580786552-ub2tb8t20undsm1o0t76acabn3kjv3gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rechargeDirectLogin',
  );
}
